"""empty message

Revision ID: 2c7b7e7b5cc7
Revises: 9fc3761bef39
Create Date: 2024-02-17 00:26:35.471801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7b7e7b5cc7'
down_revision = '9fc3761bef39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)

    # ### end Alembic commands ###
